{
  message: "server connection error Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/",
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'cluster0-shard-00-00.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-00.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74845027,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 54.156.7.210:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 54.156.7.210:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '54.156.7.210',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster0-shard-00-01.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-01.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74845020,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 34.206.181.173:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 34.206.181.173:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '34.206.181.173',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster0-shard-00-02.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-02.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74845022,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 34.197.224.93:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 34.197.224.93:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '34.197.224.93',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-phs5f0-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  level: 'error',
  stack: "MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n" +
    '    at _handleConnectionErrors (D:\\New Mission 2023\\Next Level Main Project\\University Management Project\\node_modules\\mongoose\\lib\\connection.js:792:11)\n' +
    '    at NativeConnection.openUri (D:\\New Mission 2023\\Next Level Main Project\\University Management Project\\node_modules\\mongoose\\lib\\connection.js:767:11)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  label: 'right now!',
  timestamp: '2023-06-11T09:52:55.348Z'
}
{
  message: "server connection error Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/",
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'cluster0-shard-00-00.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-00.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74922733,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 54.156.7.210:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 54.156.7.210:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '54.156.7.210',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster0-shard-00-01.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-01.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74922734,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 34.206.181.173:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 34.206.181.173:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '34.206.181.173',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'cluster0-shard-00-02.v4fkr.mongodb.net:27017' => ServerDescription {
        address: 'cluster0-shard-00-02.v4fkr.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 74922731,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ETIMEDOUT 34.197.224.93:27017
            at connectionFailureError (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:491:14)
            at TLSSocket.<anonymous> (D:\New Mission 2023\Next Level Main Project\University Management Project\node_modules\mongodb\src\cmap\connect.ts:392:16)
            at Object.onceWrapper (node:events:628:26)
            at TLSSocket.emit (node:events:513:28)
            at emitErrorNT (node:internal/streams/destroy:151:8)
            at emitErrorCloseNT (node:internal/streams/destroy:116:3)
            at processTicksAndRejections (node:internal/process/task_queues:82:21) {
          cause: Error: connect ETIMEDOUT 34.197.224.93:27017
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
            errno: -4039,
            code: 'ETIMEDOUT',
            syscall: 'connect',
            address: '34.197.224.93',
            port: 27017
          },
          [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-phs5f0-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  level: 'error',
  stack: "MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/\n" +
    '    at _handleConnectionErrors (D:\\New Mission 2023\\Next Level Main Project\\University Management Project\\node_modules\\mongoose\\lib\\connection.js:792:11)\n' +
    '    at NativeConnection.openUri (D:\\New Mission 2023\\Next Level Main Project\\University Management Project\\node_modules\\mongoose\\lib\\connection.js:767:11)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)',
  label: 'right now!',
  timestamp: '2023-06-11T09:54:13.075Z'
}
{
  level: 'error',
  label: 'right now!',
  timestamp: '2023-06-11T09:59:55.466Z'
}
